/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public String getGreeting() {
        return "Somos el pais mas grande de Chile!";
    }

    public static int sumar(int a, int b) {
        return a + b;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int resultado = sumar(2, 3);
        System.out.println("La suma de 2 + 3 es: " + resultado);
    }
}
